
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * **************************************************
 * Program Name: CIS400_W0_BaseApplication.java Programmer's Name: Brittany
 * Reath Program Description: Look Pretty, Take user input, do calculations,
 * Communicate with MySQL DataBase, return data to user. Landscaping order
 * Display *********************************************************
 */
/**
 *
 * @author Brittany
 */
public class SystemMainGUI extends javax.swing.JFrame {

    /**
     * Creates new form PickingGUI
     */
    public SystemMainGUI() {
        initComponents();
        //center the form
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(204, 230, 255));
        //loadOrders();

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btgStock = new javax.swing.ButtonGroup();
        rdoWarehouse1 = new javax.swing.JCheckBox();
        rdoEquipDepot = new javax.swing.JCheckBox();
        lblAllowStock = new javax.swing.JLabel();
        txtKeywords = new javax.swing.JTextField();
        lblKeyWords = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        txtToolName = new javax.swing.JTextField();
        lblToolName = new javax.swing.JLabel();
        cboType = new javax.swing.JComboBox<>();
        lblType = new javax.swing.JLabel();
        jScrollPane24 = new javax.swing.JScrollPane();
        txaPartSummary = new javax.swing.JTextArea();
        txtVendor = new javax.swing.JTextField();
        cboCategory = new javax.swing.JComboBox<>();
        lblPartSummary = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        btnPreview = new javax.swing.JButton();
        lblInstructions3 = new javax.swing.JLabel();
        lblVendorCode = new javax.swing.JLabel();
        cboEmployee = new javax.swing.JComboBox<>();
        cmbSkillLevel = new javax.swing.JComboBox<>();
        lblEmployee = new javax.swing.JLabel();
        lblSkillLevel = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        lclCost = new javax.swing.JLabel();
        txtVendorCode = new javax.swing.JTextField();
        btnCreatePartNumber = new javax.swing.JButton();
        lblVendor = new javax.swing.JLabel();
        rdoWarehouse2 = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btgStock.add(rdoWarehouse1);
        rdoWarehouse1.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        rdoWarehouse1.setText("Warehouse 01");

        btgStock.add(rdoEquipDepot);
        rdoEquipDepot.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        rdoEquipDepot.setText("Equipment Depot");

        lblAllowStock.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        lblAllowStock.setText("Allow Stock at:");

        txtKeywords.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        txtKeywords.setSelectionColor(new java.awt.Color(0, 153, 51));

        lblKeyWords.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        lblKeyWords.setText("Key Words:");

        txtDescription.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N

        lblDescription.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        lblDescription.setText("Description:");

        txtToolName.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        txtToolName.setSelectionColor(new java.awt.Color(0, 153, 51));
        txtToolName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToolNameActionPerformed(evt);
            }
        });

        lblToolName.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        lblToolName.setText("Tool Name:");

        cboType.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        cboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hand Tools", "Power Tools", "Testing Equipment", "Hardware", "Accessories", "Implements of Mass Destruction" }));

        lblType.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        lblType.setText("Type:");

        txaPartSummary.setEditable(false);
        txaPartSummary.setColumns(20);
        txaPartSummary.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        txaPartSummary.setLineWrap(true);
        txaPartSummary.setRows(5);
        txaPartSummary.setWrapStyleWord(true);
        txaPartSummary.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txaPartSummary.setFocusable(false);
        txaPartSummary.setRequestFocusEnabled(false);
        jScrollPane24.setViewportView(txaPartSummary);

        txtVendor.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        txtVendor.setSelectionColor(new java.awt.Color(0, 153, 51));

        cboCategory.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        cboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipment", "Materials" }));

        lblPartSummary.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        lblPartSummary.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPartSummary.setText("Part Summary:");

        lblCategory.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        lblCategory.setText("Category:");

        btnPreview.setBackground(new java.awt.Color(170, 213, 255));
        btnPreview.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        btnPreview.setText("Preview");
        btnPreview.setToolTipText("Gotta double check your work!");
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });

        lblInstructions3.setFont(new java.awt.Font("Candara", 0, 36)); // NOI18N
        lblInstructions3.setText("New Inventory Information:");

        lblVendorCode.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        lblVendorCode.setText("Vendor Code:");

        cboEmployee.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        cboEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Vinny G.", "Frank V.", "Ricky P.", "Alex V.", "C.J. R.", "Nick S.", "Tony O." }));

        cmbSkillLevel.setFont(new java.awt.Font("Candara", 0, 30)); // NOI18N
        cmbSkillLevel.setForeground(new java.awt.Color(51, 153, 0));
        cmbSkillLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1", "2", "3", "4", "5" }));
        cmbSkillLevel.setPreferredSize(new java.awt.Dimension(95, 60));

        lblEmployee.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        lblEmployee.setText("Employee:");

        lblSkillLevel.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        lblSkillLevel.setText("Skill Level:");

        txtCost.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        txtCost.setSelectionColor(new java.awt.Color(0, 153, 51));

        lclCost.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        lclCost.setText("Cost:");

        txtVendorCode.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        txtVendorCode.setSelectionColor(new java.awt.Color(0, 153, 51));

        btnCreatePartNumber.setBackground(new java.awt.Color(170, 213, 255));
        btnCreatePartNumber.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        btnCreatePartNumber.setText("Create Part Number");
        btnCreatePartNumber.setToolTipText("The \"Go\" Button");
        btnCreatePartNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePartNumberActionPerformed(evt);
            }
        });

        lblVendor.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        lblVendor.setText("Vendor:");

        btgStock.add(rdoWarehouse2);
        rdoWarehouse2.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        rdoWarehouse2.setText("Warehouse 02");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblKeyWords, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtKeywords))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDescription))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblToolName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtToolName))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCategory)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblInstructions3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAllowStock, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoEquipDepot, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoWarehouse1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoWarehouse2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lclCost, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtCost))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblVendor)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVendorCode, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSkillLevel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtVendorCode)
                                    .addComponent(cmbSkillLevel, 0, 153, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(145, 145, 145)
                                .addComponent(lblPartSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(698, 698, 698)
                        .addComponent(btnCreatePartNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblType)
                            .addComponent(cboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblToolName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtToolName, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDescription))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblKeyWords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKeywords, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAllowStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdoEquipDepot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdoWarehouse1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rdoWarehouse2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblVendor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblVendorCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVendorCode, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lclCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblSkillLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbSkillLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addComponent(btnPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEmployee)
                                .addComponent(cboEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPartSummary, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInstructions3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane24))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreatePartNumber)
                .addContainerGap(769, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtToolNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtToolNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToolNameActionPerformed

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
       // validate the inputs
        if (validateInputs() == false) {
            return;    // end the method if validation failed
        }

        // create the Customer object and show the information
        Inventory newPart = createPartNumber();
        txaPartSummary.setText(newPart.preview());
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void btnCreatePartNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePartNumberActionPerformed
        createNewPartNumber();
    }//GEN-LAST:event_btnCreatePartNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemMainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgStock;
    private javax.swing.JButton btnCreatePartNumber;
    private javax.swing.JButton btnPreview;
    private javax.swing.JComboBox<String> cboCategory;
    private javax.swing.JComboBox<String> cboEmployee;
    private javax.swing.JComboBox<String> cboType;
    private javax.swing.JComboBox<String> cmbSkillLevel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JLabel lblAllowStock;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblInstructions3;
    private javax.swing.JLabel lblKeyWords;
    private javax.swing.JLabel lblPartSummary;
    private javax.swing.JLabel lblSkillLevel;
    private javax.swing.JLabel lblToolName;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblVendor;
    private javax.swing.JLabel lblVendorCode;
    private javax.swing.JLabel lclCost;
    private javax.swing.JCheckBox rdoEquipDepot;
    private javax.swing.JCheckBox rdoWarehouse1;
    private javax.swing.JCheckBox rdoWarehouse2;
    private javax.swing.JTextArea txaPartSummary;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtKeywords;
    private javax.swing.JTextField txtToolName;
    private javax.swing.JTextField txtVendor;
    private javax.swing.JTextField txtVendorCode;
    // End of variables declaration//GEN-END:variables

   
    private boolean validateInputs() {
                
        String sEmpName = cboEmployee.getSelectedItem().toString();
        String sCategory = cboCategory.getSelectedItem().toString();
        String sType = cboType.getSelectedItem().toString();
        String sToolName = txtToolName.getText();
        String sDescription = txtDescription.getText();
        String sKeywords = txtKeywords.getText();
        String sVendor = txtVendor.getText();
        String sVendorCode = txtVendorCode.getText();
        String sCost = txtCost.getText();
        String sSkillLevel = cmbSkillLevel.getSelectedItem().toString();
        
        if (btgStock.getSelection() == null) {
            JOptionPane.showMessageDialog(this,
                    "Error. Please select where stock is available.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if (sEmpName.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Error. Please select a Name.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            cboEmployee.requestFocusInWindow();
            return false;
        }
        
        if (sCategory.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Error. Please select a Category.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            cboCategory.requestFocusInWindow();
            return false;
        }
        
        if (sType.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Error. Please select a Type.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            cboType.requestFocusInWindow();
            return false;
        }
        
        if (sToolName.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Error. Please ent a tool name.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            txtToolName.requestFocusInWindow();
            return false;
        }
        
        if (sDescription.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Error. Please enter a description.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            txtDescription.requestFocusInWindow();
            return false;
        }
        
        if (sKeywords.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Error. Please enter keywords.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            txtKeywords.requestFocusInWindow();
            return false;
        }
        
        if (sVendor.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Error. Please enter a vendor.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            txtVendor.requestFocusInWindow();
            return false;
        }
        
        if (sVendorCode.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Error. Please enter a vendor code.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            txtVendorCode.requestFocusInWindow();
            return false;
        }
        
        if (sCost.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Error. Please enter a cost.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            txtCost.requestFocusInWindow();
            return false;
        }
        
        if (sSkillLevel.isBlank()) {
            JOptionPane.showMessageDialog(this,
                    "Error. Please select a Skill Level.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            cmbSkillLevel.requestFocusInWindow();
            return false;
        }
        
        // check to see if the vendor code is a valid number
        try {
            Double.parseDouble(sVendorCode);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vendor must be a number",
                    "Vendor Error", JOptionPane.ERROR_MESSAGE);
            txtVendorCode.setText("");
            txtVendorCode.requestFocusInWindow();
            return false;
        }
        
        if (Double.parseDouble(sVendorCode) <= 0) {
            JOptionPane.showMessageDialog(this, "Vendor Code must be greater than 0",
                    "Error", JOptionPane.ERROR_MESSAGE);
            txtVendorCode.setText("");
            txtVendorCode.requestFocusInWindow();
            return false;
        }
        
        try {
            Double.parseDouble(sCost);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cost must be a number",
                    "Error", JOptionPane.ERROR_MESSAGE);
            txtVendorCode.setText("");
            txtVendorCode.requestFocusInWindow();
            return false;
        }
        
        if (Double.parseDouble(sCost) <= 0) {
            JOptionPane.showMessageDialog(this, "Cost must be greater than 0",
                    "Error", JOptionPane.ERROR_MESSAGE);
            txtCost.setText("");
            txtCost.requestFocusInWindow();
            return false;
        }
        
        return true;
    }

    private Inventory createPartNumber() {
        String empName = cboEmployee.getSelectedItem().toString();
        String category = cboCategory.getSelectedItem().toString();
        String type = cboType.getSelectedItem().toString();
        String toolName = txtToolName.getText();
        String description = txtDescription.getText();
        String keywords = txtKeywords.getText();
        String allowStock = "";
        String vendor = txtVendor.getText();
        int vendorCode = Integer.parseInt(txtVendorCode.getText());
        double cost = Double.parseDouble(txtCost.getText());
        String skillLevel = cmbSkillLevel.getSelectedItem().toString();
        
        if( rdoEquipDepot.isSelected()){
            allowStock = "Equipment Depot";
        } 
        else if (rdoWarehouse1.isSelected()) {
            allowStock = "Warehouse 01";
        }else if (rdoWarehouse2.isSelected()) {
            allowStock = "Warehouse 02";
        }else {
            JOptionPane.showMessageDialog(this, 
                    "Please select: Allow Stock at");
        }
        
        Inventory newPart = new Inventory(empName, category, type, toolName,
        description, keywords, allowStock, vendor, vendorCode, cost, skillLevel);
        
        return newPart;
    }
    
    private void createNewPartNumber() {
        if (validateInputs() == false) {
            return;    // end the method if validation failed
        }
        Inventory newPart = createPartNumber();

        try {
            InventoryIO data = new InventoryIO();
            data.add(newPart);
            JOptionPane.showMessageDialog(this, "Inventory added to DB");

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error. ClassNotFound Catch.Database driver not found.", "Driver Not Found", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error. SQL Catch." + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
